name: Docker build
on:
    pull_request:
      types: [opened, synchronize, reopened]
jobs:
  dockerhub:
    uses: usdot-fhwa-stol/actions/.github/workflows/docker.yml@main
    with:
      tag_name_suffix: noetic
